name: Bug Report
description: Create a report to help us improve SafeSave.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened?
      placeholder: I clicked the Blue light but nothing happened...
    validations:
      required: true
  - type: dropdown
    id: light-color
    attributes:
      label: What color was the Traffic Light?
      options:
        - Green (Synced)
        - Orange (Push Changes)
        - Blue (Get Updates)
        - Red (Conflict)
        - Grey (Offline)
    validations:
      required: true
  - type: dropdown
    id: source-control
    attributes:
      label: Source Control Provider
      options:
        - Git (Beta)
        - PlasticSCM
        - Perforce
  - type: textarea
    id: logs
    attributes:
      label: Output Log
      description: Please copy any text from the Unreal Output Log that mentions "SourceControl".
      render: shell